<?php /* Smarty version 2.6.18, created on 2015-10-27 09:21:08
         compiled from vc2k8_activex_proj.tpl */ ?>
<?php echo '<?xml'; ?>
 version="1.0" encoding="Windows-1252"<?php echo '?>'; ?>

<VisualStudioProject
	ProjectType="Visual C++"
	Version="9.00"
	Name="<?php echo $this->_tpl_vars['projName']; ?>
"
	ProjectGUID="<?php echo $this->_tpl_vars['GUID']; ?>
"
	Keyword="AtlProj"
	TargetFrameworkVersion="196613"
	>
	<Platforms>
		<Platform
			Name="Win32"
		/>
	</Platforms>
	<ToolFiles>
	</ToolFiles>
	<Configurations>
		<Configuration
			Name="Debug|Win32"
			OutputDirectory="<?php echo $this->_tpl_vars['projectOffset']; ?>
../Link/VC2k8.$(ConfigurationName).$(PlatformName)"
			IntermediateDirectory="$(OutDir)/$(ProjectName)"
			ConfigurationType="2"
			UseOfATL="1"
			ATLMinimizesCRunTimeLibraryUsage="false"
			CharacterSet="1"
			>
			<Tool
				Name="VCPreBuildEventTool"
			/>
			<Tool
				Name="VCCustomBuildTool"
			/>
			<Tool
				Name="VCXMLDataGeneratorTool"
			/>
			<Tool
				Name="VCWebServiceProxyGeneratorTool"
			/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="_DEBUG"
				MkTypLibCompatible="false"
				TargetEnvironment="1"
				GenerateStublessProxies="true"
				TypeLibraryName="$(IntDir)/IEWebGamePlugin.tlb"
				HeaderFileName="..\..\..\web\source\activex\IEWebGamePlugin_i.h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="..\..\..\web\source\activex\IEWebGamePlugin_i.c"
				ProxyFileName="..\..\..\web\source\activex\IEWebGamePlugin_p.c"
				ValidateParameters="true"
			/>
			<Tool
				Name="VCCLCompilerTool"
				Optimization="0"
				PreprocessorDefinitions="WIN32;_WINDOWS;_DEBUG;_USRDLL;_CRT_SECURE_NO_WARNINGS"
				MinimalRebuild="true"
				BasicRuntimeChecks="3"
				RuntimeLibrary="<?php echo $this->_tpl_vars['projRuntimeDebug']; ?>
"
				UsePrecompiledHeader="2"
				WarningLevel="3"
				DebugInformationFormat="4"
			/>
			<Tool
				Name="VCManagedResourceCompilerTool"
			/>
			<Tool
				Name="VCResourceCompilerTool"
				PreprocessorDefinitions="_DEBUG"
				Culture="1033"
				AdditionalIncludeDirectories="$(IntDir)"
			/>
			<Tool
				Name="VCPreLinkEventTool"
			/>
			<Tool
				Name="VCLinkerTool"
            PerUserRedirection="true"
				RegisterOutput="true"
				IgnoreImportLibrary="true"
				LinkIncremental="2"
				ModuleDefinitionFile="..\..\..\web\source\activex\IEWebGamePlugin.def"
				GenerateDebugInformation="true"
				SubSystem="2"
				TargetMachine="1"
				OutputFile="<?php echo $this->_tpl_vars['projectOffset']; ?>
../../<?php echo $this->_tpl_vars['gameFolder']; ?>
/<?php echo $this->_tpl_vars['projOutName']; ?>
.dll"
				ProgramDatabaseFile="$(OutDir)/$(ProjectName)_DEBUG.pdb"
                AdditionalDependencies = "version.lib"
			/>
			<Tool
				Name="VCALinkTool"
			/>
			<Tool
				Name="VCManifestTool"
			/>
			<Tool
				Name="VCXDCMakeTool"
			/>
			<Tool
				Name="VCBscMakeTool"
			/>
			<Tool
				Name="VCFxCopTool"
			/>
			<Tool
				Name="VCAppVerifierTool"
			/>
			<Tool
				Name="VCPostBuildEventTool"
			/>
		</Configuration>
		<Configuration
			Name="Release|Win32"
			OutputDirectory="<?php echo $this->_tpl_vars['projectOffset']; ?>
../Link/VC2k8.$(ConfigurationName).$(PlatformName)"
			IntermediateDirectory="$(OutDir)/$(ProjectName)"
			ConfigurationType="2"
			UseOfATL="1"
			ATLMinimizesCRunTimeLibraryUsage="false"
			CharacterSet="1"
			>
			<Tool
				Name="VCPreBuildEventTool"
			/>
			<Tool
				Name="VCCustomBuildTool"
			/>
			<Tool
				Name="VCXMLDataGeneratorTool"
			/>
			<Tool
				Name="VCWebServiceProxyGeneratorTool"
			/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="NDEBUG"
				MkTypLibCompatible="false"
				TargetEnvironment="1"
				GenerateStublessProxies="true"
				TypeLibraryName="$(IntDir)/IEWebGamePlugin.tlb"
				HeaderFileName="..\..\..\web\source\activex\IEWebGamePlugin_i.h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="..\..\..\web\source\activex\IEWebGamePlugin_i.c"
				ProxyFileName="..\..\..\web\source\activex\IEWebGamePlugin_p.c"
				ValidateParameters="true"
			/>
			<Tool
				Name="VCCLCompilerTool"
				Optimization="2"
				PreprocessorDefinitions="WIN32;_WINDOWS;NDEBUG;_USRDLL;_CRT_SECURE_NO_WARNINGS"
				RuntimeLibrary="<?php echo $this->_tpl_vars['projRuntimeRelease']; ?>
"
				UsePrecompiledHeader="2"
				WarningLevel="3"
				DebugInformationFormat="0"
			/>
			<Tool
				Name="VCManagedResourceCompilerTool"
			/>
			<Tool
				Name="VCResourceCompilerTool"
				PreprocessorDefinitions="NDEBUG"
				Culture="1033"
				AdditionalIncludeDirectories="$(IntDir)"
			/>
			<Tool
				Name="VCPreLinkEventTool"
			/>
			<Tool
				Name="VCLinkerTool"
            PerUserRedirection="true"
				RegisterOutput="true"
				IgnoreImportLibrary="true"
				LinkIncremental="1"
				ModuleDefinitionFile="..\..\..\web\source\activex\IEWebGamePlugin.def"
				GenerateDebugInformation="false"
				SubSystem="2"
				OptimizeReferences="2"
				EnableCOMDATFolding="2"
				TargetMachine="1"
				OutputFile="<?php echo $this->_tpl_vars['projectOffset']; ?>
../../<?php echo $this->_tpl_vars['gameFolder']; ?>
/<?php echo $this->_tpl_vars['projOutName']; ?>
.dll"
                AdditionalDependencies = "version.lib"
			/>
			<Tool
				Name="VCALinkTool"
			/>
			<Tool
				Name="VCManifestTool"
			/>
			<Tool
				Name="VCXDCMakeTool"
			/>
			<Tool
				Name="VCBscMakeTool"
			/>
			<Tool
				Name="VCFxCopTool"
			/>
			<Tool
				Name="VCAppVerifierTool"
			/>
			<Tool
				Name="VCPostBuildEventTool"
			/>
		</Configuration>
	</Configurations>
	<References>
	</References>
	<Files>
		<Filter
			Name="Source Files"
			Filter="cpp;c;cc;cxx;def;odl;idl;hpj;bat;asm;asmx"
			>
			<File
				RelativePath="..\..\..\web\source\activex\dllmain.cpp"
				>
				<FileConfiguration
					Name="Debug|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						UsePrecompiledHeader="0"
						CompileAsManaged="0"
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						UsePrecompiledHeader="0"
						CompileAsManaged="0"
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGameCtrl.cpp"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGamePlugin.cpp"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGameWindow.cpp"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGamePlugin.def"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGamePlugin.idl"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\common\webCommon.cpp"
				>
				<FileConfiguration
					Name="Release|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						UsePrecompiledHeader="0"
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Debug|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						UsePrecompiledHeader="0"
					/>
				</FileConfiguration>
            </File>
			<File
				RelativePath="..\..\..\web\source\activex\stdafx.cpp"
				>
				<FileConfiguration
					Name="Debug|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						UsePrecompiledHeader="1"
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						UsePrecompiledHeader="1"
					/>
				</FileConfiguration>
			</File>
		</Filter>
		<Filter
			Name="Header Files"
			Filter="h;hpp;hxx;hm;inl;inc;xsd"
			>
			<File
				RelativePath="..\..\..\web\source\activex\dllmain.h"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGameCtrl.h"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGameWindow.h"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\Resource.h"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\stdafx.h"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\targetver.h"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\common\webConfig.h"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\common\webCommon.h"
				>
			</File>
		</Filter>
		<Filter
			Name="Resource Files"
			Filter="rc;ico;cur;bmp;dlg;rc2;rct;bin;rgs;gif;jpg;jpeg;jpe;resx;tiff;tif;png;wav"
			>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGameCtrl.bmp"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGameCtrl.rgs"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGamePlugin.rc"
				>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGamePlugin.rgs"
				>
			</File>
		</Filter>
		<Filter
			Name="Generated Files"
			SourceControlFiles="false"
			>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGamePlugin_i.c"
				>
				<FileConfiguration
					Name="Debug|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						UsePrecompiledHeader="0"
						CompileAsManaged="0"
					/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						UsePrecompiledHeader="0"
						CompileAsManaged="0"
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="..\..\..\web\source\activex\IEWebGamePlugin_i.h"
				>
			</File>
		</Filter>
	</Files>
	<Globals>
	</Globals>
</VisualStudioProject>